---
title: "World Cup Summary Scoreboard"
format: html
editor: visual
output-file: index.html
---

```{r load, echo=FALSE, warning=FALSE, message=FALSE, include = FALSE}

library(readxl)
library(tidyverse)
library(writexl)
library(robotoolbox)
library(kableExtra)

###
#Tasks:
# Golden boot and finalist + winner guess



Sys.setenv("KOBOTOOLBOX_URL" = "https://eu.kobotoolbox.org/") # or 
Sys.setenv("KOBOTOOLBOX_TOKEN" = "ce3ff25f11586de5e5463439d5b0629924aa037e")

kobo_asset_version_list("aRXZr7eSw3zhFEdX9TKsBP")

players <- read_excel("./otherquest.xlsx", sheet = "choices")

scoretest <- kobo_submissions("aRXZr7eSw3zhFEdX9TKsBP", all_versions = FALSE, select_multiple_label = FALSE)%>%
  select( -sumgoalgame9, -diffgoalgame9,-resultgamegame9)%>%
  select(where(~!all(is.na(.) )),
         -matches("^final_.*"),
         -matches("^game[0-9]{2,3}scorer_.*")
         )%>%
  mutate(Player = str_to_sentence(Player),
         final = str_replace_all(final, " " , " - ")
  )%>%
  arrange(Player)
  

gamelistfull <- read_xlsx("./FIFAScheduleResults.xlsx")

gamelist <- gamelistfull%>%
  mutate(Matchname = paste0(Phase, " : ", Match))%>%
  select( matchnumber, Matchname, Match )

finalandgoldenboot <- scoretest%>%
  select(Player, Final = final, `World Champion 2026` = winner, goldenboot)%>%
  filter(!is.na(Final))%>%
  left_join(players %>% select(name, `Golden Boot` = label), by = c("goldenboot" = "name"))%>%
  mutate( `World Champion 2026` = recode( `World Champion 2026`,
                          ESP = "🏆 Spain",
                          FRA = "🏆 France",
                          PRT = "🏆 Portugal",
                          ARG = "🏆 Argentina"),
         `Golden Boot` = str_replace_all(`Golden Boot`, c("\\d" = "", " - " = "",  c(
           "ESP" = "Spain - 👟  ⚽ ",
           "FRA" = "France - 👟  ⚽ ",
           "NOR" = "Norway - 👟  ⚽ "  ,
           "ARG" = "Argentina - 👟  ⚽ ",  
           "PRT" = "Portugal - 👟  ⚽ ",  
           "ENG" = "England  - 👟  ⚽ ")
           )),
         Final =  str_replace_all(Final, c("ESP" = "Spain", 
                                           "FRA" = "France",
                                           "ARG" = "Argentina",
                                           "NLD" = "Netherlands",
                                           "PRT" = "Portugal",
                                           "DEU" = "Germany",
                                           "ENG" = "England")))%>%
  select(-goldenboot)



```

## 📊 Scoreboard as of `r format(Sys.Date(), '%B %d, %Y')`

```{r scoreboard, warning=FALSE, message=FALSE, echo = FALSE}

# Group Phase
fullscore <- scoretest%>%
  filter(round == "1st" |round == "2nd" | round == "3rd")%>%
  # Remove empty columns (all NA or all empty string)
  select(where(~!all(is.na(.) ))) %>%
  # Keep only the columns you want
  select(Player,
         round,
         starts_with("scoregame"),
         starts_with("sumgoal"),
         starts_with("diffgoal"),
         starts_with("resultgame"))%>%
  pivot_longer(
    cols = starts_with(c("scoregame", "sumgoalgame", "diffgoalgame", "resultgame")),
    names_to = c(".value", "game"),
    names_pattern = "(score|sumgoal|diffgoal|resultgame)(.*)"
  )%>%
  mutate( predictioncode = case_when(diffgoal == 0 ~ "D",
                                     diffgoal > 0 ~ "W1",
                                     diffgoal < 0 ~ "W2", TRUE ~ NA))%>%
  right_join( gamelistfull%>%filter(!is.na(Resultcode) & grepl("Group", Phase))%>% select(matchnumber,ResultGame, ScorerGame, Resultcode, DiffGame, Date), by = c("game" = "matchnumber"))%>%
  mutate(`Prediction Result` = case_when(  score==ResultGame ~ "Correct score",
                                          diffgoal == DiffGame & Resultcode != "D" ~ "Correct goal difference",
                                          predictioncode == Resultcode ~ "Correct result",
                                         TRUE ~ NA
                                             ),
         Points = case_when( `Prediction Result` ==  "Correct score"  & (round == "1st" | round == "2nd" |round == "3rd" ) ~ 10,
                             `Prediction Result` ==  "Correct goal difference"  & (round == "1st" | round == "2nd" |round == "3rd" ) ~ 5,
                             `Prediction Result` ==  "Correct result"  & (round == "1st" | round == "2nd" |round == "3rd" ) ~ 3,                            TRUE ~ NA)) 

# knock-out stage

fullscoreko <- scoretest%>%
  filter(round != "1st"  & round != "2nd" & round != "3rd"  )%>%
   select(where(~!all(is.na(.) ))) %>%
   rename_with(~ gsub("game([0-9]+)scorer", "goalgame\\1", .x))%>%
  group_by(round, Player)%>%
  summarise(across(everything(), ~ paste(na.omit(.x), collapse = "")))%>%
  # Keep only the columns you want
  select(round,
         Player, 
         starts_with("scoregame"), 
         starts_with("sumgoal"), 
         starts_with("diffgoal"), 
         starts_with("resultgame"), 
         starts_with("goal"),
         starts_with("draw"))%>%
  pivot_longer(
    cols = starts_with(c("scoregame", "sumgoalgame", "diffgoalgame", "resultgame", "goal", "draw")),
    names_to = c(".value", "game"),
    names_pattern = "(score|sumgoal|diffgoal|resultgame|goal|draw)(.*)"
  )%>%
  mutate( predictioncode = case_when(diffgoal == 0 ~ "D", 
                                     diffgoal == "" ~ "EMPTY",
                                     diffgoal > 0 ~ "W1",
                                     diffgoal < 0 ~ "W2", 
                                     TRUE ~ NA))%>%
  right_join( gamelistfull%>%filter(!is.na(Resultcode), !grepl("Group", Phase))%>% select(matchnumber,ResultGame, ScorerGame, Resultcode, DiffGame, Date, PenaltyWin, PWinCode), by = c("game" = "matchnumber"))%>%
  mutate(`Prediction Result` = case_when(  # Exact score
    score==ResultGame ~ "Correct score", 
    # Exact goal difference
    diffgoal == DiffGame & Resultcode != "D" ~ "Correct goal difference",
    # Correct result
    predictioncode == Resultcode ~ "Correct result",
    TRUE ~ NA),
    PenaltyWinnerBonus = case_when(# Correct draw + penalty winner correct
      predictioncode == Resultcode & draw == PenaltyWin ~ "Penalty winner bonus",
      # Wrong result but  penalty winner correct
      predictioncode == PWinCode ~ "Penalty winner bonus",
    TRUE ~ NA)
)%>%
  select(Player, Date, game,`Prediction Result`, PenaltyWinnerBonus , round)%>%
  pivot_longer(
    cols = c(`Prediction Result`, PenaltyWinnerBonus),
    values_to = "Prediction Result"
  ) %>%
  select(-name) %>%
  filter(!is.na(`Prediction Result`) & `Prediction Result`!= "") %>%
  group_by(Player, Date, game,round) %>%
  distinct(`Prediction Result`) %>%
  ungroup()%>%
  mutate(Pointspre = case_when( `Prediction Result` ==  "Correct score" ~ 10,
                      `Prediction Result` ==  "Correct goal difference"   ~ 5,
                      `Prediction Result` ==  "Correct result"  ~ 3,  
                      `Prediction Result` ==  "Correct result and penalty winner"  ~ 4,
                      `Prediction Result` ==  "Penalty winner bonus"  ~ 1,
                      TRUE ~ NA),
  Points = case_when( round == "r32" ~ Pointspre * 1.25, 
                      round == "r16" ~ Pointspre * 1.5,
                      round == "r4" ~ Pointspre * 1.75,
                      round == "r2" ~ Pointspre * 2) 
  )

# Correct scorer Table

scorerknockout <- scoretest%>%
  filter(round != "1st"  & round != "2nd" & round != "3rd"  )%>%
  select(where(~!all(is.na(.) ))) %>%
  rename_with(~ gsub("game([0-9]+)scorer", "goalgame\\1", .x))%>%
  group_by(Player, round)%>%
  summarise(across(everything(), ~ paste(na.omit(.x), collapse = "")))%>%
  # Keep only the columns you want
  select(round,
         Player,  
         starts_with("goal"))%>%
  pivot_longer(
    cols = starts_with(c("goal")),
    names_to = c(".value", "game"),
    names_pattern = "(goal)(.*)"
  )%>%
  separate_wider_delim(
  goal, 
  delim = " ", 
  names_sep = "_", 
  too_few = "align_start"
) %>%
  # Pivot to longer format
  pivot_longer(
    cols = starts_with("goal_"),
    names_to = NULL,
    values_to = "goal",
    values_drop_na = TRUE
  )

actualscorer <- gamelistfull%>%
  filter(!grepl("Group", Phase))%>%
  select(matchnumber, ScorerGame, Date)%>%
  separate_wider_delim(
    ScorerGame, 
    delim = ", ", 
    names_sep = "_", 
    too_few = "align_start"
  ) %>%
  # Pivot to longer format
  pivot_longer(
    cols = starts_with("Scorer"),
    names_to = NULL,
    values_to = "ScorerGame",
    values_drop_na = TRUE
  )%>%
  ungroup()%>%  
  summarise(Buts = n(), .by = c(Date, matchnumber, ScorerGame))

correctscorertable <- scorerknockout%>%
  inner_join(actualscorer, by = c("game" = "matchnumber", "goal" = "ScorerGame"))%>%
  mutate( Points = case_when(round == "r32" ~ Buts * 4 * 1.25,
                             round == "r16" ~ Buts * 4 * 1.5,
                             round == "r4" ~ Buts * 4 * 1.75,
                             round == "r2" ~ Buts * 4 * 2),
          `Prediction Result` = "Correct scorer")



# Merge all tables

fullscorett <- bind_rows(fullscore%>%select(Player,`Prediction Result`, Points, Date),
                         fullscoreko%>%select(Player,`Prediction Result`, Points, Date),
                         correctscorertable %>%select(Player, `Prediction Result`, Date, Points) )

# Merge and final scoring

Playerpredictsummary <-fullscorett%>%
  filter(!is.na(`Prediction Result`))%>%
  group_by(Player, `Prediction Result`) %>%
  summarise(Count = n()
 ) %>%
  pivot_wider(
    id_cols = Player,  # Keep Player as first column
    names_from = `Prediction Result`,
    values_from = Count,
    values_fill = 0  )%>%
  select(Player,
         `Exact score` = `Correct score`,
         `Correct goal difference`,
         `Correct result`,
         `Correct scorer`,
        #  `Correct result and penalty winner`, 
         `Penalty winner bonus`)


Playerpredictpoints <-fullscorett%>%
  filter(!is.na(`Prediction Result`))%>%
  group_by(Player) %>%
  summarise(Points = sum(Points, na.rm = TRUE)
  ) %>%
  full_join(Playerpredictsummary, by = "Player")%>%
  arrange(desc(Points),desc(`Exact score`), Player )


  Playerpredictpoints%>%
    kbl(
    caption = "<b>Score board</b>",
    align = 'c',
    booktabs = TRUE
  ) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = FALSE,
    position = "center",
    font_size = 14
  ) %>%
  row_spec(0, background = "#2c3e50", color = "white", bold = TRUE) %>%
  column_spec(1, background = "#e8eaf6", color = "#1a237e", bold = TRUE) %>% 
  column_spec(2, background =  "#F08784", color = "#0c5460", bold = TRUE) %>%
  column_spec(3, background = "#AAC0C4", color = "#0c5460") %>%
  column_spec(4, background = "#d1ecf1", color = "#0c5460") %>%
  column_spec(5, background = "#d1ecf1", color = "#0c5460") %>%
  column_spec(6, background = "#d1ecf1", color = "#0c5460") %>%
    column_spec(7, background = "#d1ecf1", color = "#0c5460")


```

```{r leaders, warning=FALSE, message=FALSE, echo = FALSE, fig.width= 14}

Date <- c(unique(fullscorett$Date))
Player <- c(unique(fullscorett$Player))



template <- expand.grid(Date = Date, Player = Player)
  
Leaders <-fullscorett%>% 
  full_join(template, by = c("Player", "Date"))%>%
  group_by(Player, Date)%>%
  summarise(Points = sum(Points, na.rm =TRUE)) %>%
  mutate(Date = as.POSIXct(Date, format = "%d/%m"))%>%
 group_by(Player) %>%
  arrange(Date, .by_group = TRUE) %>%
  mutate(cumulative_points = cumsum(Points)) %>%
  ungroup() %>%
  group_by(Date) %>%
  mutate(
    rank_num = rank(desc(cumulative_points), ties.method = "last"),
    Ranking = case_when(
      rank_num == 1 ~ "1st",
      rank_num == 2 ~ "2nd",
      rank_num == 3 ~ "3rd",
      TRUE ~ paste0(rank_num, "th")),
      Date = substr(Date, 6, 10)
    ) %>%
  arrange(Date, Ranking) %>%
  ungroup()%>%
  select(Player, Date, Ranking)

leadertable <-  ggplot(Leaders, aes(x = Date, y = Player)) +
  geom_tile(aes(fill = Ranking), 
            color = "white", linewidth = 0.5) +
  geom_text(aes(label = Ranking), size = 3.5, fontface = "bold") +
  scale_fill_manual(
    values = c(
      "1st" = "gold",
      "2nd" = "#C0C0C0",
      "3rd" = "#CD7F32",
      "8th" = "#ff2c2c"
    ),
    na.value = "#d1ecf1",  # Default background for all other values
    guide = "none"
  ) +
  theme_minimal() +
  theme(
    # X-axis on top with proper alignment and bold text
    axis.text.x.top = element_text(
      angle = 45, 
      hjust = 0, 
      vjust = 0, 
      size = 7,
      face = "bold",
      margin = margin(b = 2)
    ),
    axis.text.x = element_blank(),
    # Y-axis labels bold
    axis.text.y = element_text(
      size = 9,
      face = "bold",
      margin = margin(r = 5)
    ),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    legend.position = "none",
    plot.title = element_text(
      hjust = 0.5, 
      size = 12, 
      face = "bold"
    ),
    # Reduce margins
    #plot.margin = margin(t = 1, r = 1, b = 1, l = 1)
    # Remove aspect ratio constraint
    aspect.ratio = NULL
  ) +
  scale_x_discrete(position = "top") +
  # Control the size of tiles
  coord_fixed(ratio = 0.5) +  # Adjust ratio to control tile width/height
  labs(
    title = "Evolution of positions"
  )

leadertable

```

## 🏆Final 🏆 and Golden Boot 👟⚽ prediction

```{r final, warning=FALSE, message=FALSE, echo = FALSE}

finalandgoldenboot %>%
  kbl(
    caption = "<b>Final and Golden Boot prediction</b>",
    align = 'c',
    booktabs = TRUE
  ) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = FALSE,
    position = "center",
    font_size = 14
  ) %>%
  row_spec(0, background = "#2c3e50", color = "white", bold = TRUE) %>%
  column_spec(1, background = "#e8eaf6", color = "#1a237e", bold = TRUE) %>%
  column_spec(2, background = "#d1ecf1", color = "#0c5460") %>%
  column_spec(3, background = "#d1ecf1", color = "#0c5460") %>%
  column_spec(4, background = "#fff3cd", color = "#856404", bold = TRUE) 

```

```{r goldenboot, echo=FALSE, warning=FALSE, message=FALSE}

# Extract from game list the values of the scorer, split by delimiter, count and 
# left_join to ref list

# Count occurrences of each value
goldenboot<-gamelistfull %>%
  filter(!is.na(ScorerGame))%>%
  mutate(answers = str_split(ScorerGame, ", ")) %>%
  unnest(answers) %>%
  count(answers)%>%
  left_join(players%>%select(name, full_name), by = c("answers" ="name"))%>%
  select( `Player Name` = full_name, 
          Goals = n)%>%
  mutate( `Player Name` = case_when( is.na(`Player Name`) ~ "Own Goal", 
                                     TRUE ~  `Player Name`))%>%
  slice_max(order_by = Goals, n = 5)

goldenboot%>%
  kbl(
    caption = "<b>Current top 5 scorer</b>",
    align = 'c',
    booktabs = TRUE
  ) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = FALSE,
    position = "center",
    font_size = 14
  ) %>%
  row_spec(0, background = "#2c3e50", color = "white", bold = TRUE) %>%
  column_spec(1, background = "#e8eaf6", color = "#1a237e", bold = TRUE) %>%
  column_spec(2, background = "#d1ecf1", color = "#0c5460") 
 


```

## 👨‍⚖️ 🏃‍♂️ 🥅 Group phase predictions and results

```{r printroundTT, echo=FALSE, warning=FALSE, message=FALSE,  fig.height= 15,  fig.width= 13}
scoretableround2 <- scoretest%>%
  filter(round == "1st" |round == "2nd" |round == "3rd"  )%>%
   select(where(~!all(is.na(.) ))) %>%
  group_by(Player)%>%
  summarise(across(everything(), ~ paste(na.omit(.x), collapse = "")))%>%
  # Keep only the columns you want
  select(Player, 
         starts_with("scoregame"), 
         starts_with("sumgoal"), 
         starts_with("diffgoal"), 
         starts_with("resultgame"))%>%
  pivot_longer(
    cols = starts_with(c("scoregame", "sumgoalgame", "diffgoalgame", "resultgame")),
    names_to = c(".value", "game"),
    names_pattern = "(score|sumgoal|diffgoal|resultgame)(.*)"
  )%>%
  mutate( predictioncode = case_when(diffgoal == 0 ~ "D", 
                                     diffgoal == "" ~ "EMPTY",
                                     diffgoal > 0 ~ "W1",
                                     diffgoal < 0 ~ "W2", 
                                     TRUE ~ NA))%>%
  left_join( gamelist, by = c("game" = "matchnumber"))

# Query results 
resultstableround2 <- gamelistfull%>%
  filter( !is.na(ResultGame) & grepl("Group", Phase))%>%
  select(Match, score = ResultGame,predictioncode=Resultcode)%>%
  mutate(Player = "Final Result")

plot_data2nd <- scoretableround2 %>%
  select(Match, Player, score, predictioncode) %>%
  bind_rows(resultstableround2)%>%
  mutate(
    Player  = forcats::fct_relevel(factor(Player), "Final Result", after = Inf),
    Match = factor(Match, levels = rev(unique(scoretableround2$Match))),
    predictioncode = factor(predictioncode, levels = c("W1", "D", "W2")) # Reverse for better display
  )

pround2 <- ggplot(plot_data2nd, aes(x = Player, y = Match)) +
  geom_tile(aes(fill = predictioncode, alpha = Player == "Final Result"), 
            color = "white", linewidth = 0.5) +
  geom_text(aes(label = score), size = 4.5) +
  scale_fill_manual(
    values = c(
      "W1" = "#83f28f",
      "D" = "#fff3cd",
      "W2" = "#d1ecf1"
    ),
    name = "Prediction",
    breaks = c("W1", "D", "W2")
  ) +
  scale_alpha_manual(values = c("TRUE" = 0.7, "FALSE" = 1), guide = "none") +
  # Add vertical line
  geom_vline(xintercept = which(levels(plot_data2nd$Player) == "Final Result") - 0.5,
             linewidth = 1.5, color = "black") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1.2, size = 12),
    axis.text.y = element_text(size = 12),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    legend.position = "right",
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold")
  )+
  labs(
    title = "Predictions - Group Phase",
    subtitle = "W1=Home Win, D=Draw, W2=Away Win"
  )

pround2

```

## 👨‍⚖️ 🏃‍♂️ 🥅 Knock-out phase predictions and results

```{r printroundknockout, echo=FALSE, warning=FALSE, message=FALSE, fig.width= 13, fig.height=14}
scoretableroundko <- scoretest%>%
  filter(round != "1st"  & round != "2nd" & round != "3rd"  )%>%
   select(where(~!all(is.na(.) ))) %>%
   rename_with(~ gsub("game([0-9]+)scorer", "goalgame\\1", .x))%>%
  group_by(Player)%>%
  summarise(across(everything(), ~ paste(na.omit(.x), collapse = "")))%>%
  # Keep only the columns you want
  select(Player, 
         starts_with("scoregame"), 
         starts_with("sumgoal"), 
         starts_with("diffgoal"), 
         starts_with("resultgame"), 
         starts_with("goal"),
         starts_with("draw"))%>%
  pivot_longer(
    cols = starts_with(c("scoregame", "sumgoalgame", "diffgoalgame", "resultgame", "goal", "draw")),
    names_to = c(".value", "game"),
    names_pattern = "(score|sumgoal|diffgoal|resultgame|goal|draw)(.*)"
  )%>%
  filter(!is.na(score))%>%
  mutate( predictioncode = case_when(diffgoal == 0 ~ "D", 
                                     diffgoal == "" ~ "EMPTY",
                                     diffgoal > 0 ~ "W1",
                                     diffgoal < 0 ~ "W2", 
                                     TRUE ~ NA))%>%
  left_join( gamelist, by = c("game" = "matchnumber"))%>%
  mutate(gamenumber = as.integer(str_replace(game, "game", "")))%>%
  arrange(gamenumber)

# Query results 
resultstableroundko <- gamelistfull%>%
  filter( !is.na(ResultGame) & !grepl("Group", Phase))%>%
  select(Match, score = ResultGame,predictioncode=Resultcode)%>%
  mutate(Player = "Final Result")

plot_datako <- scoretableroundko %>%
  select(Match, Player, score, predictioncode) %>%
  bind_rows(resultstableroundko)%>%
  mutate(
    Player  = forcats::fct_relevel(factor(Player), "Final Result", after = Inf),
    Match = factor(Match, levels = rev(unique(scoretableroundko$Match))),
    predictioncode = factor(predictioncode, levels = c("W1", "D", "W2")) # Reverse for better display
  )

proundko <- ggplot(plot_datako, aes(x = Player, y = Match)) +
  geom_tile(aes(fill = predictioncode, alpha = Player == "Final Result"), 
            color = "white", linewidth = 0.5) +
  geom_text(aes(label = score), size = 4.5) +
  scale_fill_manual(
    values = c(
      "W1" = "#83f28f",
      "D" = "#fff3cd",
      "W2" = "#d1ecf1"
    ),
    name = "Prediction",
    breaks = c("W1", "D", "W2")
  ) +
  scale_alpha_manual(values = c("TRUE" = 0.7, "FALSE" = 1), guide = "none") +
  # Add vertical line
  geom_vline(xintercept = which(levels(plot_datako$Player) == "Final Result") - 0.5,
             linewidth = 1.5, color = "black") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1.2, size = 12),
    axis.text.y = element_text(size = 12),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    legend.position = "right",
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold")
  ) +
  labs(
    title = "Predictions - Knock-out Stage",
    subtitle = "W1=Home Win, D=Draw, W2=Away Win"
  )+
  geom_hline(yintercept = which(levels(plot_datako$Match) == "Australia vs Egypt") - 0.5, linewidth = 1.5, color = "red")+
  geom_hline(yintercept = which(levels(plot_datako$Match) == "Switzerland vs Colombia") - 0.5, linewidth = 1.5, color = "red")+
  geom_hline(yintercept = which(levels(plot_datako$Match) == "Argentina vs Switzerland") - 0.5, linewidth = 1.5, color = "red")

proundko

```

## Upcoming games 👟

```{r games, warning=FALSE, message=FALSE, echo = FALSE}

gamelistfull %>%
  mutate(Date = as.Date(gsub("\\?", "/", Date), format = "%d/%m/%Y"))%>%
  filter(Date  >= Sys.Date() & Date <= Sys.Date() + 7 & !(Date == Sys.Date() & Time <= "12:00"))%>%
  select(Match, Date, Time)%>%
  arrange(Date, Time)%>%
  kbl(
    caption = "<b>Game for the upcoming 7 days</b>",
    align = 'c',
    booktabs = TRUE
  ) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = TRUE,
    position = "center",
    font_size = 14
  ) %>%
  row_spec(0, background = "#2c3e50", color = "white", bold = TRUE) %>%
  column_spec(1, background = "#e8eaf6", color = "#1a237e", bold = TRUE) %>%
  column_spec(2, background = "#d1ecf1", color = "#0c5460") %>%
  column_spec(3, background = "#fff3cd", color = "#856404", bold = TRUE) 



```
